// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package fourmgr

// Injectors from wire.go:

func InitializeUser() user {
	head := NewHead()
	nick := NewNick()
	fourmgrUser := NewUser(head, nick)
	return fourmgrUser
}
